-- ========================================
-- SUPABASE SEED DATA
-- ========================================
-- Purpose: Sample data for testing dashboard
-- Usage: Run after schema.sql
-- ========================================

-- Clear existing data
TRUNCATE TABLE barbershop_campaign_tracking CASCADE;
TRUNCATE TABLE barbershop_actionable_leads CASCADE;
TRUNCATE TABLE barbershop_analytics_daily CASCADE;
TRUNCATE TABLE barbershop_customers CASCADE;
TRUNCATE TABLE barbershop_transactions CASCADE;

-- Insert sample transactions
INSERT INTO barbershop_transactions (
  transaction_date, customer_phone, customer_name, service_tier, 
  upsell_items, atv_amount, discount_amount, customer_area, capster_name,
  is_coupon_redeemed, is_google_review_asked
) VALUES
  -- December 2025 data
  ('2025-12-01 10:30:00+07', '081234567890', 'Budi Santoso', 'Basic', NULL, 20000, 0, 'Patikraja', 'Owner', FALSE, FALSE),
  ('2025-12-02 11:15:00+07', '082345678901', 'Agus Wijaya', 'Premium', 'Hair Tonic', 45000, 0, 'Kedungrandu', 'Owner', FALSE, TRUE),
  ('2025-12-03 13:00:00+07', '083456789012', 'Dedi Kurniawan', 'Mastery', 'Coloring, Massage', 75000, 0, 'Banyumas', 'Owner', FALSE, FALSE),
  ('2025-12-04 14:30:00+07', '081234567890', 'Budi Santoso', 'Basic', NULL, 20000, 0, 'Patikraja', 'Owner', FALSE, FALSE),
  ('2025-12-05 16:00:00+07', '084567890123', 'Eko Prasetyo', 'Premium', 'Hair Tonic', 40000, 5000, 'Kebumen', 'Owner', TRUE, TRUE),
  ('2025-12-06 10:00:00+07', '085678901234', 'Fauzi Rahman', 'Mastery', 'Coloring, Beard Trim', 80000, 0, 'Patikraja', 'Owner', FALSE, FALSE),
  ('2025-12-07 12:30:00+07', '086789012345', 'Gunawan Saputra', 'Premium', 'Hair Tonic', 45000, 0, 'Banyumas', 'Owner', FALSE, TRUE),
  ('2025-12-08 15:00:00+07', '087890123456', 'Hendra Wijaya', 'Basic', NULL, 20000, 0, 'Kedungrandu', 'Owner', FALSE, FALSE),
  ('2025-12-09 09:30:00+07', '088901234567', 'Irfan Hakim', 'Premium', 'Hair Tonic, Massage', 50000, 0, 'Patikraja', 'Owner', FALSE, FALSE),
  ('2025-12-10 11:00:00+07', '081234567890', 'Budi Santoso', 'Basic', NULL, 20000, 0, 'Patikraja', 'Owner', FALSE, FALSE),
  
  -- More recent data (mid-December)
  ('2025-12-11 10:30:00+07', '082345678901', 'Agus Wijaya', 'Premium', 'Hair Tonic', 45000, 0, 'Kedungrandu', 'Owner', FALSE, TRUE),
  ('2025-12-12 14:00:00+07', '089012345678', 'Joko Susilo', 'Mastery', 'Coloring', 70000, 0, 'Banyumas', 'Owner', FALSE, FALSE),
  ('2025-12-13 16:30:00+07', '083456789012', 'Dedi Kurniawan', 'Premium', 'Hair Tonic', 45000, 0, 'Banyumas', 'Owner', FALSE, TRUE),
  ('2025-12-14 11:00:00+07', '084567890123', 'Eko Prasetyo', 'Premium', NULL, 35000, 0, 'Kebumen', 'Owner', FALSE, FALSE),
  ('2025-12-15 13:30:00+07', '085678901234', 'Fauzi Rahman', 'Mastery', 'Massage', 65000, 0, 'Patikraja', 'Owner', FALSE, FALSE),
  ('2025-12-16 15:00:00+07', '081234567890', 'Budi Santoso', 'Premium', 'Hair Tonic', 40000, 5000, 'Patikraja', 'Owner', TRUE, TRUE),
  ('2025-12-17 10:00:00+07', '090123456789', 'Kemal Arifin', 'Basic', NULL, 20000, 0, 'Kedungrandu', 'Owner', FALSE, FALSE),
  ('2025-12-17 12:00:00+07', '091234567890', 'Lukman Hakim', 'Premium', 'Hair Tonic', 45000, 0, 'Patikraja', 'Owner', FALSE, FALSE);

-- Note: Customer profiles and analytics will be auto-generated by Edge Functions
-- Run these Edge Functions after inserting transactions:
-- 1. update-customer-profiles
-- 2. generate-actionable-leads
-- 3. calculate-daily-analytics (if you create this function)

-- Sample campaign (optional)
INSERT INTO barbershop_campaign_tracking (
  campaign_name, campaign_type, target_segment, total_targets,
  start_date, end_date, status, messages_sent, responses_received,
  conversions, campaign_cost, revenue_generated, created_by, notes
) VALUES
  (
    'December Comeback Campaign',
    'retention',
    'High-Value Churn Risk',
    15,
    '2025-12-01',
    '2025-12-31',
    'active',
    12,
    8,
    5,
    0,
    225000,
    'Owner',
    'WA campaign untuk pelanggan high-value yang sudah >45 hari tidak datang'
  );

-- Verify inserted data
SELECT 
  'Transactions' AS table_name, 
  COUNT(*) AS row_count 
FROM barbershop_transactions

UNION ALL

SELECT 
  'Campaigns' AS table_name, 
  COUNT(*) AS row_count 
FROM barbershop_campaign_tracking;

-- Show revenue summary
SELECT 
  DATE_TRUNC('month', transaction_date) AS month,
  COUNT(*) AS total_transactions,
  SUM(net_revenue) AS total_revenue,
  ROUND(AVG(atv_amount), 0) AS avg_atv
FROM barbershop_transactions
GROUP BY DATE_TRUNC('month', transaction_date)
ORDER BY month DESC;
